export const COMPUTER_MOVE_DELAY_MS = 2500;
export const FIRST_MOVE_URGENT_SECONDS = 10;
export const COMPUTER_FALLBACK_MOVE_MS = 6000;
export const MATCH_END_FALLBACK_MS = 5000;
export const BOARD_ENTRANCE_WAVE_MS = 160;
export const BOARD_ENTRANCE_WAVE_COUNT = 4;
export const BOARD_ENTRANCE_LANDING_MS = 600;
