export const SOCKET_EVENTS = {
 CONNECT: "connect",
 CONNECT_ERROR: "connect_error",
 SESSION_REPLACED: "session:replaced",
 DEVICE_APPROVED: "device_approved",
 GAME_ACTIVE: "game:active",
 GAME_STATE: "game:state",
 GAME_REJOIN_DECLINED: "game:rejoin:declined",
 POOL_JOIN: "pool:join",
 POOL_LEAVE: "pool:leave",
 POOL_TIMEOUT: "pool:timeout",
 MATCHED: "matched",
 MATCH_STARTED: "match:started",
 ROOM_CREATE: "room:create",
 ROOM_JOIN: "room:join",
 ROOM_START: "room:start",
 ROOM_CANCEL: "room:cancel",
 ROOM_LEAVE: "room:leave",
 ROOM_LEFT: "room:left",
 WALLET_UPDATED: "wallet:updated",
 TRANSACTION_COMPLETED: "transaction:completed",
} as const;
