export const SOCKET_EVENTS = {
 CONNECT: "connect",
 CONNECT_ERROR: "connect_error",
 SESSION_REPLACED: "session_replaced",
 DEVICE_APPROVED: "device_approved",
 GAME_ACTIVE: "game_active",
 GAME_STATE: "game_state",
 GAME_REJOIN_DECLINED: "game_rejoin_declined",
 GAME_END: "game_end",
 POOL_JOIN: "pool_join",
 POOL_LEAVE: "pool_leave",
 POOL_TIMEOUT: "pool_timeout",
 POOL_UPDATED: "pool_updated",
 MATCHED: "matched",
 MATCH_STARTED: "match_started",
 ROOM_CREATE: "room_create",
 ROOM_JOIN: "room_join",
 ROOM_START: "room_start",
 ROOM_CANCEL: "room_cancel",
 ROOM_LEAVE: "room_leave",
 ROOM_LEFT: "room_left",
 WALLET_UPDATED: "wallet_updated",
 TRANSACTION_COMPLETED: "transaction_completed",
} as const;
